import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Frame from '@/components/molecules/Frame/Frame'
import ProfileCard from '@/components/molecules/ProfleCard/Profile'
import { Modal } from '@/components/molecules/Modal/Modal'
import { CreateGallerieForm } from '@/components/molecules/CreateGallerieForm/CreateGallerieForm'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })


const gallery = [
  {
    id: 1,
    src: '/Human.png'
  },
  {
    id: 2,
    src: '/PXL_20221115_122219617.jpg'
  },
  {
    id: 3,
    src: '/PXL_20221115_122228380.jpg'
  },
  {
    id: 4,
    src: '/Human.png'
  },
  {
    id: 5,
    src: '/PXL_20221115_122219617.jpg'
  },
  {
    id: 6,
    src: '/PXL_20221115_122228380.jpg'
  },
  {
    id: 7,
    src: '/Human.png'
  },
  {
    id: 8,
    src: '/PXL_20221115_122219617.jpg'
  },
  {
    id: 9,
    src: '/PXL_20221115_122228380.jpg'
  },
]

const profile = {
  firstname: 'Guillaume',
  lastname: 'RAK'
}



export default function Home() {
const [isModalOpen, setModalOpen] = useState(false);

const CloseModal = () => {
  setModalOpen(false);
};

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal formComponent={<CreateGallerieForm onClose={CloseModal}/>} isModalOpen={isModalOpen} handleModalClose={CloseModal}/>
      <main className={styles.main}>
        <ProfileCard firstname={profile.firstname} lastname={profile.lastname}/>
        <button onClick={() => setModalOpen(true)}>open modal</button>
        <div className={styles.content}>
        {gallery.map(item => (
            <Frame key={item.id}  src={item.src} width={100} height={100} alt=''/>
        ))}
        </div>
      </main>
    </>
  )
}
